### ISSUE TITLE
css files - Rainbell English

### ISSUE THREAD

**Issue by cheolhom** [Rainbell129/Obsidian-Homepage#10]
I can't seem to find where the css files are for the Homepage for Rainbell English

**Comment by Rainbell129** [comment]
<img width="1004" alt="Screen Shot 2022-08-03 at 10 10 54" src="https://user-images.githubusercontent.com/58488160/182509068-3a49ce97-8e19-46fa-8d42-eb42b97bbce3.png">

**Comment by cheolhom** [comment]
thank you
