### ISSUE TITLE
我使用您的库，重命名了各种文件夹，ios打开每次都会生成 40 - Obsidian/主页/00.主页 的空文件，但mac不会，请问怎么解决。

### ISSUE THREAD

**Issue by DoshideDK** [Rainbell129/Obsidian-Homepage#13]
我使用您的库，重命名了各种文件夹，ios打开每次都会生成 40 - Obsidian/主页/00.主页 的空文件，但mac不会，请问怎么解决。

**Comment by Rainbell129** [comment]
看一下homepage插件的各种设置，还有工作区重新保存一下试试。
On Aug 11, 2022, 13:13 +0800, hongdaikun ***@***.***>, wrote:

我使用您的库，重命名了各种文件夹，ios打开每次都会生成 40 - Obsidian/主页/00.主页 的空文件，但mac不会，请问怎么解决。
