### ISSUE TITLE
您好，请问可以提供一下【Rainbell库用户实例】的模板或仓库地址吗？

### ISSUE THREAD

**Issue by Zzzchh** [Rainbell129/Obsidian-Homepage#15]
您好，示例库很漂亮，我借鉴了您的库，并做了一些细微调整，无意间看到了【Rainbell库用户实例】，发现有些地方有一点心动，可以提供一下他们的示例库或仓库地址吗，谢谢

**Comment by Rainbell129** [comment]
都是私人库哦，这个没有公布出来的，可以私下里跟他们联系请求许可。

**Comment by Zzzchh** [comment]
感谢回复，可以麻烦告知他们的GitHub用户名吗

**Comment by Zzzchh** [comment]
> 都是私人库哦，这个没有公布出来的，可以私下里跟他们联系请求许可。

感谢回复，可以麻烦告知他们的GitHub用户名吗

**Comment by Rainbell129** [comment]
我也不太清楚，这些都是他们的微信名，你可以来群里找他们

**Comment by Zzzchh** [comment]
> 我也不太清楚，这些都是他们的微信名，你可以来群里找他们 Message ID: ***@***.***>

十分感谢！
