### ISSUE TITLE
图书馆

### ISSUE THREAD

**Issue by Jacobxz** [Rainbell129/Obsidian-Homepage#16]
我想吧这个迁移到自己库里，请问这个在那个文件里
`cssClasses: cards cards-align-bottom cards-2-3 table-100`
![image](https://user-images.githubusercontent.com/48195963/187066916-f94d5c10-fa54-403d-a438-c8ec3c15c824.png)

**Comment by Rainbell129** [comment]
css snippets里应该有个卡片视图的css文件
