### ISSUE TITLE
booknote plugin?

### ISSUE THREAD

**Issue by chiumax** [Rainbell129/Obsidian-Homepage#17]
Hi, i saw in some of your notes' frontmatter that you reference "booknote", what is it?

thanks so much for this repo, been super helpful :)

**Comment by Rainbell129** [comment]
It is a PDF plugin I used but its tutorial is in Chinese. You can check this for further information if you can read Chinese.

https://kknwfe6755.feishu.cn/docs/doccnBfbtETItLHMmbDBGBRdPrh
