### ISSUE TITLE
Homepage Button Colors

### ISSUE THREAD

**Issue by mothnmoon** [Rainbell129/Obsidian-Homepage#20]
Not sure if this will be seen, yet I have a question. 

Where in the CSS snippet is the section where we can change the colors for the Homepage buttons (the ones that have links to the daily/weekly notes, that are grey and blue in the default template)

I looked through the css and could not find it, and I was afraid to mess anything up accidentally.

**Comment by Rainbell129** [comment]
There's a way to find out where. Do you know how to use developer's mode?

**Comment by Rainbell129** [comment]
<img width="685" alt="Screen Shot 2023-01-09 at 15 22 00" src="https://user-images.githubusercontent.com/58488160/211257890-b527143f-b722-4b8d-ad67-3226b9c81929.png">

You toggle developer tools, and click on the circled button. 

<img width="804" alt="Screen Shot 2023-01-09 at 15 22 27" src="https://user-images.githubusercontent.com/58488160/211258071-2f882b6d-13f8-42b6-b000-8bbd027af895.png">

Then you find the place you'd like to change and click on it.

**Comment by mothnmoon** [comment]
ah thank you! i wish i saw this sooner before my computer decided to delete my entire edited vault and i have no backup to rely on ... i appreciate the help though!

**Comment by Rainbell129** [comment]
Oh, I'm sorry to hear this...
