### ISSUE TITLE
Homepage buttons don't show in Live Preview

### ISSUE THREAD

**Issue by nbycoder** [Rainbell129/Obsidian-Homepage#22]
I'm not sure if they're *meant* to work with Live Preview or not; in Reading view it works fine, however Edit Mode + Live Preview would be ideal to me, as I use Templater to get my daily tasks on my homepage. All the CSS snippets are loaded and I'm using the Blue Topaz theme, as recommended.

![image](https://user-images.githubusercontent.com/90400844/229547065-be940af7-a16f-4cfc-947d-0f2511161efa.png)

**Comment by Rainbell129** [comment]
This is what the editing view now looks like, yes. I guess in my personal use I do not generally use editing mode on homepage since there are just too much code that even with lp it took forever to load. So I just stick it to preview with advanced url links like "xxxx&view=preview"
