### ISSUE TITLE
Homepage didn't work well.

### ISSUE THREAD

**Issue by akenoshi** [Rainbell129/Obsidian-Homepage#24]
The homepage didn't work as well. It just  shows as follow:
![Snipaste_2024-01-14_20-24-43](https://github.com/Rainbell129/Obsidian-Homepage/assets/94778685/94babee5-89db-4c1a-bd24-9bd6828ff8f0)

**Comment by Rainbell129** [comment]
Fixed. Please refer to the newest source code of Rainbell English or Rainbell Vault.
