### ISSUE TITLE
我想问下，PROJECT TRACKING里的红色嘴唇怎么去掉

### ISSUE THREAD

**Issue by PandaK404** [Rainbell129/Obsidian-Homepage#27]
![image](https://github.com/Rainbell129/Obsidian-Homepage/assets/83934795/0676f6a5-0a7d-4f35-934c-7447340836ec)

插件非常好，就是这个红色的嘴唇该怎么去掉呢？我找了圈没找到

**Comment by Rainbell129** [comment]
哈哈，可以看一下css片段里sharetype.css
在 2024年7月10日 +0800 18:14，PandaK404 ***@***.***>，写道：

image.png (view on web)<https://github.com/Rainbell129/Obsidian-Homepage/assets/83934795/0676f6a5-0a7d-4f35-934c-7447340836ec>

插件非常好，就是这个红色的嘴唇该怎么去掉呢？我找了圈没找到
