### ISSUE TITLE
如何保证启动Obsidian时右侧边栏中的Calendar和Tasks Timeline保持展开状态？

### ISSUE THREAD

**Issue by Yuran-Zhao** [Rainbell129/Obsidian-Homepage#29]
您好，我自己写了一个homepage，但是每次打开Obsidian时都需要自己从右侧边栏手动先split down再打开另一个。我注意到您的仓库打开时这两部分是直接展开呈现出来的，请问这个是怎么实现的呢？

**Comment by Rainbell129** [comment]
不太理解，什么叫做split down?
在 2024年7月21日 +0800 09:57，Yuran Zhao ***@***.***>，写道：

您好，我自己写了一个homepage，但是每次打开Obsidian时都需要自己从右侧边栏手动先split down再打开另一个。我注意到您的仓库打开时这两部分是直接展开呈现出来的，请问这个是怎么实现的呢？

**Comment by Yuran-Zhao** [comment]
现在启动后右侧边栏是这样的：
![startup](https://github.com/user-attachments/assets/bd239cb2-96eb-48f3-8bb0-d290ef7539f7)

进行split-down操作：
![split-down](https://github.com/user-attachments/assets/0f11297e-7d53-493a-b45e-0c9a23973fcc)

split down完成后：
![after split-down](https://github.com/user-attachments/assets/4d5f625c-d45c-43e9-b25a-4f74b8300c3b)

然后我需要手动将上半部分改为Calendar，不知道能否在启动时就实现下图的效果呢：
![desire](https://github.com/user-attachments/assets/761bac55-5b90-4efb-b31f-1e592253b838)

**Comment by Rainbell129** [comment]
可以的，你在homepage或者工作区（workspace）插件中调整一下主页布局并且保存就行。我好久没调整了忘了具体是哪个插件了

**Comment by Yuran-Zhao** [comment]
谢谢您的帮助！

激活workspace插件之后进行布局调整并保存，然后在homepage中设置启动页面为workspace类型即可。

之前我的Calendar插件用了beta版本，加载保存的工作区之后会出现重复统计内容的情况，改用您仓库中的版本就可以了。
