### ISSUE TITLE
你好，很喜欢你这个风格，能否把整个模板库分享下，自己做太难了

### ISSUE THREAD

**Issue by ghost** [Rainbell129/Obsidian-Homepage#4]
<img width="960" alt="iShot2022-03-03 09 51 59" src="https://user-images.githubusercontent.com/55862635/156505911-14c85d7d-54c4-4824-a372-4bf925aab93f.png">
<img width="920" alt="iShot2022-03-03 09 51 48" src="https://user-images.githubusercontent.com/55862635/156505948-e7166928-32ed-46e3-b5ce-1bcb0df180ee.png">

**Comment by Rainbell129** [comment]
你做的已经很好了，基本功能都有了。之后等我的工作流再成熟一点，会放库上来，现在还有点零碎。

**Comment by ghost** [comment]
> 你做的已经很好了，基本功能都有了。之后等我的工作流再成熟一点，会放库上来，现在还有点零碎。

期待 ing

**Comment by XMFlight** [comment]
好强

> <img alt="iShot2022-03-03 09 51 59" width="960" src="https://user-images.githubusercontent.com/55862635/156505911-14c85d7d-54c4-4824-a372-4bf925aab93f.png">
> 
> <img alt="iShot2022-03-03 09 51 48" width="920" src="https://user-images.githubusercontent.com/55862635/156505948-e7166928-32ed-46e3-b5ce-1bcb0df180ee.png">

**Comment by Y1YU** [comment]
请问下面的热力图是怎么实现的

**Comment by jasonho1308** [comment]
> 请问下面的热力图是怎么实现的

[Activity History](obsidian://show-plugin?id=obsidian-activity-history) 
obsidian://show-plugin?id=obsidian-activity-history

**Comment by Rainbell129** [comment]
已分享示例库，可以去releases下载。
