### ISSUE TITLE
进度条无法在dataviewjs中正确显示

### ISSUE THREAD

**Issue by Steven-AA** [Rainbell129/Obsidian-Homepage#5]
我添加了progress 相关的css， 直接写的进度条可以显示了

![sp20220406_130427_583](https://user-images.githubusercontent.com/22387129/161899553-a80fd84f-1261-4cb3-89fe-775fd024bbb0.png)

，但dataviewjs里面无法正确显示，是我遗漏了什么吗？

![sp20220406_130336_394](https://user-images.githubusercontent.com/22387129/161899450-a2420c72-39e0-4812-98a6-b51b7a46cf78.png)

**Comment by Rainbell129** [comment]
你用的是新代码吗？

Sent with a Spark<https://sparkmailapp.com/source?from=signature>

**Comment by Steven-AA** [comment]
dataviewjs的代码用的是`Project Tracking.md`里的，最新的

**Comment by Steven-AA** [comment]
试出来了，我漏掉了`groupedCount:: true`， 但这个是必要的吗？`toTheProgressBar`  是不是应该在 `if (groupedCount) ` 外面执行？

**Comment by Rainbell129** [comment]
我还真没注意，因为我这个是直接建立在人家的代码上的。我查一下逻辑。

Sent with a Spark<https://sparkmailapp.com/source?from=signature>

**Comment by Steven-AA** [comment]
```
output.map(row => {
//row[1] = insert1000sep(row[1]);
row[2] = toTheProgressBar(row[2]);
return row;
});
```
我把上面的代码移到了`if (groupedCount) `外面，我这是可以正常工作的，不知道会不会影响`groupCount`相关的内容。

**Comment by Rainbell129** [comment]
我觉得不会

Sent with a Spark<https://sparkmailapp.com/source?from=signature>
On Apr 6, 2022, 2:43 PM +0800, 张卿云 ***@***.***>, wrote:

output.map(row => {

//row[1] = insert1000sep(row[1]);

row[2] = toTheProgressBar(row[2]);

return row;

});



我把上面的代码移到了if (groupedCount) 外面，我这是可以正常工作的，不知道会不会影响groupCount相关的内容。
