### ISSUE TITLE
按照教程操作后homepage报错

### ISSUE THREAD

**Issue by tutivog** [Rainbell129/Obsidian-Homepage#7]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/13778638/164226744-ca6b9a68-7fdd-4e12-b409-a28810db4fc5.png">

**Comment by Rainbell129** [comment]
把Show改成ShowI 我印象里改过了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: tutivog ***@***.***>
发送时间: Wednesday, April 20, 2022 8:06:17 PM
收件人: Rainbell129/Obsidian-Homepage ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Rainbell129/Obsidian-Homepage] 按照教程操作后homepage报错 (Issue #7)


[image]<https://user-images.githubusercontent.com/13778638/164226744-ca6b9a68-7fdd-4e12-b409-a28810db4fc5.png>

―

**Comment by Rainbell129** [comment]
我去看了一下，没有改，我现在更新了。你这边最好把homepage setting.css也换成最新的。我又稍微调过一些css了。

**Comment by tutivog** [comment]
替换了新的css还有homepage 现在分栏那个部分正常了 但是还是一直会有unable to find section #日记 的错误，但是我在当天的笔记已经有添加日记的tag：
<img width="605" alt="image" src="https://user-images.githubusercontent.com/13778638/164228095-d6756bbe-2e3d-4e92-8a81-cac4d2fa2d35.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/13778638/164228121-b8d43cca-2dea-4ecc-ae88-e750133e7e9d.png">

**Comment by Rainbell129** [comment]
这个需要你在日记里写一个#日记 标题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: tutivog ***@***.***>
发送时间: Wednesday, April 20, 2022 8:14:57 PM
收件人: Rainbell129/Obsidian-Homepage ***@***.***>
抄送: Y. Wang ***@***.***>; Comment ***@***.***>
主题: Re: [Rainbell129/Obsidian-Homepage] 按照教程操作后homepage报错 (Issue #7)


替换了新的css还有homepage 现在分栏那个部分正常了 但是还是一直会有unable to find section #日记 的错误，但是我在当天的笔记已经有添加日记的tag：
[image]<https://user-images.githubusercontent.com/13778638/164228095-d6756bbe-2e3d-4e92-8a81-cac4d2fa2d35.png>
[image]<https://user-images.githubusercontent.com/13778638/164228121-b8d43cca-2dea-4ecc-ae88-e750133e7e9d.png>

―

**Comment by Rainbell129** [comment]
不是ta g

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Y. Wang ***@***.***>
发送时间: Wednesday, April 20, 2022 8:53:20 PM
收件人: Rainbell129/Obsidian-Homepage ***@***.***>; Rainbell129/Obsidian-Homepage ***@***.***>
抄送: Comment ***@***.***>
主题: Re: [Rainbell129/Obsidian-Homepage] 按照教程操作后homepage报错 (Issue #7)

这个需要你在日记里写一个#日记 标题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: tutivog ***@***.***>
发送时间: Wednesday, April 20, 2022 8:14:57 PM
收件人: Rainbell129/Obsidian-Homepage ***@***.***>
抄送: Y. Wang ***@***.***>; Comment ***@***.***>
主题: Re: [Rainbell129/Obsidian-Homepage] 按照教程操作后homepage报错 (Issue #7)


替换了新的css还有homepage 现在分栏那个部分正常了 但是还是一直会有unable to find section #日记 的错误，但是我在当天的笔记已经有添加日记的tag：
[image]<https://user-images.githubusercontent.com/13778638/164228095-d6756bbe-2e3d-4e92-8a81-cac4d2fa2d35.png>
[image]<https://user-images.githubusercontent.com/13778638/164228121-b8d43cca-2dea-4ecc-ae88-e750133e7e9d.png>

**Comment by tutivog** [comment]
啊明白了 感谢指导🙏
