### ISSUE TITLE
[Question] what plugin is used for this quick access pane?

### ISSUE THREAD

**Issue by andrewcrook** [Rainbell129/Obsidian-Homepage#8]
Hi 

I am just wondering what plugin is used for this quick access pane?

<img width="179" alt="image" src="https://user-images.githubusercontent.com/803618/169703266-d45df874-a9d2-4d5b-88e6-1dda3dd3171a.png">

**Comment by talios** [comment]
@andrewcrook No plugin needed - create a standard note called "Quick Access", then when it's showing - clicking'n'drag from the upper-left (left of the title, depending on theme there should be a grab handle icon or something - or blank in the minimal theme) - then simply drag it down to the left side panel.

**Comment by Rainbell129** [comment]
You can change the icon using the css snippet sidepane (credit to Cuman). You should get an svg code and change the filename referenced within the codeblocks into the names of your markdown file.

**Comment by andrewcrook** [comment]
@talios  @Rainbell129   oh wow I never thought to try that I presumed that tool areas were off bounds.
That’s great to know. Especially when you can get rid of some plugins and use dataview plugin instead.
Thank you both.
