### ISSUE TITLE
Buttons on the top of the page

### ISSUE THREAD

**Issue by Michel-Giesecke** [Rainbell129/Obsidian-Homepage#9]
Hey, I really love what you did here and I have been trying to implement parts of the setup into my own vault. However, I can't get the MOC buttons at the top to work. No matter what I do they are shown as a list even when I download the example vault and open it without changing anything.
Does somebody have an idea as to what the issue is? I really like that specific part of the setup

**Comment by Rainbell129** [comment]
Open the example vault with Obsidian and take a screenshot of the homepage. I'll have a look.

**Comment by Michel-Giesecke** [comment]
![Screenshot 2022-06-20 112053](https://user-images.githubusercontent.com/22278663/174570293-b74ed4a0-0686-46d2-8903-bd31c5593505.png)

This is what the homepage looks like for me, without having changed anything

**Comment by Rainbell129** [comment]
Hmmm strange. try downloading another vault in Chinese and see. It really looks like the `homepage setting.css` is missing but it should've automatically been included. Check whether you've disabled the css snippet.

**Comment by Michel-Giesecke** [comment]
I tried with some of the other vaults now, but either get the same issue or it can't even find the homepage file when pressing the homepage button in the sidebar.
Where would I need to enable the css snippet? Maybe that really is the issue and I just haven't found the right setting yet

**Comment by Michel-Giesecke** [comment]
I just found it. My lack of experience with snippets held me back. I didn't know about the page within the settings in which you can enable/disable specific snippets. Thank you for trying to help this quickly and sorry that it was my mistake in the end 😅

**Comment by Rainbell129** [comment]
ok solved then
